name: ci-check

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - name: linter
        run: make lint

        env:
          CI: true
